04.Web/web_project5/posts/urls.py
from django.urls import path
from posts import views

app_name="posts"
urlpatterns = [
    path("feeds/", views.feeds, name="feeds"),
    path("comment_add/", views.comment_add, name="comment_add"),
    path("comment_delete/<int:comment_id>/", views.comment_delete, name="comment_delete"),
    path("post_add/", views.post_add, name="post_add"),
    path("tags/<str:tag_name>/", views.tags, name="tags"),
    path("<int:post_id>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/like/", views.post_like, name = "post_like"),
]

04.Web/web_project5/pystagram/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from pystagram import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.index),
    path("users/", include("users.urls")),
    path("posts/", include("posts.urls")),
]

urlpatterns += static(
    prefix = settings.MEDIA_URL,
    document_root = settings.MEDIA_ROOT,
)

04.Web/web_project5/users/urls.py
from django.urls import path
from users import views



app_name="users"

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("signup/", views.signup, name="signup"),
    path("<int:user_id>/profile/", views.profile, name="profile"),
    path("<int:user_id>/followers", views.followers, name="followers"),
    path("<int:user_id>/following", views.following, name="following"),
    path("<int:user_id>/follow/", views.follow, name="follow"),
    
]

04.Web/web_project5/posts/models.py
from django.db import models



# Create your models here.
class Post(models.Model):
    user = models.ForeignKey("users.user", 
                             verbose_name="작성자", 
                             on_delete=models.CASCADE)
    content = models.TextField("내용", blank=True)
    created = models.DateTimeField("작성일시", auto_now_add=True)
    tags = models.ManyToManyField("posts.HashTag",
                                  verbose_name="해시태그 목록",
                                  blank=True)

    def __str__(self):
        return f"{self.user.username}의 Post(id:{self.id})"



class PostImage(models.Model):
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    photo = models.ImageField("사진", upload_to="post")


class Comment(models.Model):
    user = models.ForeignKey("users.User",
                             verbose_name="작성자",
                             on_delete=models.CASCADE)
    post = models.ForeignKey(Post,
                             verbose_name="포스트",
                             on_delete=models.CASCADE)
    content = models.TextField("내용")
    created = models.DateTimeField("작성일시", auto_now_add=True)


class HashTag(models.Model):
    name = models.CharField("태그명", max_length=50)

    def __str__(self):
        return self.name
    


    

04.Web/web_project5/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.shortcuts import redirect

# Create your models here.
class User(AbstractUser):
    profile_image = models.ImageField("프로필 이미지", upload_to="users/prorile", 
                                      blank=True)
    short_description = models.TextField("소개글", blank=True)
    like_posts = models.ManyToManyField(
        "posts.Post",
        verbose_name ="좋아요 누른 post목록",
        related_name="like_users",
        blank=True, 
    )
    following= models.ManyToManyField(
        "self",
        verbose_name="팔로우 중인 사용자들",
        related_name="followers",
        symmetrical=False,
        through="users.Relationship",
    )
    def __str__(self):
        return self.username
    

class Relationship(models.Model):
    from_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우를 요청한 사용자",
        related_name="following_relationships",
        on_delete=models.CASCADE,
    )

    to_user = models.ForeignKey(
        "users.User",
        verbose_name="팔로우 요청의 대상",
        related_name="follower_relationships",
        on_delete=models.CASCADE,
    )

    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"관계({self.from_user} -> {self.to_user})"
    
class KaKaoView(view):
    def get(self, request):
        kakao_api"https://kauth.kakao.com/oauth/authorize?response_type=code"
        redirect_uri = "https://127.0.0.1:8000/users/kakao/callback"
        client_id = "5d9674e8857ca4ccf50a61b8d2c25cb0"

        return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")
    

04.Web/web_project5/users/forms.py
from django import forms
from users.models import User
from django.core.exceptions import ValidationError

class LoginForm(forms.Form):
    username = forms.CharField(
        min_length=3,
        widget=forms.TextInput(
            attrs={"placeholder": "사용자명(3자리이상)"},
        )
    )
    password = forms.CharField(
        min_length=4,
        widget=forms.PasswordInput(
            attrs={"placeholder": "비밀번호(4자리이상)"}
        )
    )

class SignupForm(forms.Form):
    username = forms.CharField()
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)
    profile_image = forms.ImageField()
    short_description = forms.CharField()


    def clean_username(self):
        username = self.cleaned_data["username"]

        if User.objects.filter(username=username).exists():
            raise ValidationError(f"입력한 사용자명({username})은 이미 사용 중입니다")
        
        return username
    
    def clean(self):
        password1 = self.cleaned_data["password1"]
        password2 = self.cleaned_data["password2"]

        if password1 != password2:
            # password2 필드에 오류추가
            self.add_error("password2",
                           "비밀번호와 비밀번호 확인값이 다릅니다")
            
    def save(self):
        username = self.cleaned_data["username"]
        password1 = self.cleaned_data["password1"]
        profile_image = self.cleaned_data["profile_image"]
        short_description = self.cleaned_data["short_description"]

        user = User.objects.creat_user(
            username = username,
            password = password1,
            profile_image = profile_image,
            short_description = short_description,

        )
        return user

04.Web/web_project5/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from users.forms import LoginForm, SignupForm
from django.contrib.auth import authenticate, login, logout
from users.models import User
from django.http import HttpResponseRedirect
from django.urls import reverse




# Create your views here.
def login_view(request):
    # 이미 로그인되어 있다면 
    if request.user.is_authenticated:
        return redirect("posts:feeds")

    if request.method == "POST":
        # LoginForm인스턴스 만들면서 입력데이터는  request.POST사용
        form = LoginForm(data = request.POST)
    
        #LoginsForm에 들어온 데이터가 적절한지 유효성 검사
       # print("form.is_valid():", form.is_valid())

        #유효성 검사 이후에는 cleaned_data에서 데이터 가져와 사용
       #print("form.cleaned_data:", form.cleaned_data)
        #context = {"form" : form}

        # LoginForm에 전달된 데이터가 유효하다면
        if form.is_valid():
            #username, password 값을 가져와 변수에 할당
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
        
            #username, password에 해당하는 사용자 있는지 검사
            user = authenticate(username=username, password=password)

            # 해당 사용자 존재한다면
            if user:
                #로그인 후 피드페이지로 redirect
                login(request, user)
                return redirect("posts:feeds")
            
            #사용자가 없다면 "실패했습니다" form에 에러 추가
            else:
                form.add_error(None, "아이디 혹은 비밀번호가 틀렸습니다")
           
        #실패한 경우 다시 LoginForm 사용한 로그인 페이지 렌더링
        context = {"form": form}

    else:
        # LoginForm 인스턴스 생성
        form = LoginForm()

    # 생성한 LoginForm 인스턴스를 템플릿에 "form"이라는 키로 전달
    context = {
        "form":form,
    }

    
    return render(request, "users/login.html", context)


def logout_view(request):
    # logout 함수 호출에 request 전달
    logout(request)

    #logout 처리 후, 로그인 페이지로 이동
    return redirect("users:login")

def signup(request):
    if request.method == "POST":
        form = SignupForm(data=request.POST, files=request.FILES)
        #Form 에러가 없다면 form의 save()메서드로 사용자 생성
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("posts:feeds")


       
    # GET  요청시에는 빈 Form 보여줌
    else:
        # SignupForm 인스턴스 생성, Template 전달
        form = SignupForm()
    
    # context 전달되는 form은 두가지 경우가 존재
    #1. POST 요청에서 생성된 form유효하지 않은경우 
        # -> 에러를 포함한 form이 사용자에게 보여짐

    #2. GET 요청으로 빈 form이 생성
        # -> 빈 form이 사용자에게 보여짐
    context = {"form":form}
    return render(request, "users/signup.html", context)

def profile(request, user_id):
    user=get_object_or_404(User, id=user_id)
    context={
        "user":user,
    }
    return render(request, "users/profile.html", context)

def followers(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.follower_relationships.all()
    context={
        "user":user,
        "title":"Followers",
        "relationships":relationships,
    }
    return render(request,"users/followers.html", context)

def following(request, user_id):
    user = get_object_or_404(User, id=user_id)
    relationships = user.following_relationships.all()
    context={
        "user":user,
        "title":"Following",
        "relationships":relationships,
    }
    return render(request,"users/following.html", context)

def follow(request, user_id):
    # 로그인한 유저
    user = request.user
    # 팔로우 하려는 유저
    target_user = get_object_or_404(User, id=user_id)

    # 팔로우 하려는 유저가 이미 자신의 팔로잉 목록에 있는 경우
    if target_user in user.following.all():
        # 팔로잉 목록에서 제거
        user.following.remove(target_user)
    else:
        # 팔로잉 목록에 추가
        user.following.add(target_user)

    # 팔로우 토글 후 이동할 url이 전달되었다면 해당 주소로
    # 전달되지 않았다면 로그인한 유저의 프로필 페이지로 이동
    url_next = request.GET.get("next") or reverse("users:profile", args=[user.id])
    return HttpResponseRedirect(url_next)
    

04.Web/web_project5/templates/users/followers.html
{% extends 'base_profile.html' %}

{% block bottom_data %}

<div class="relationships">
    <h3>Followers</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.from_user.id %}">
                {% if relationship.from_user.profile_image %}
                    <img src="{{ relationship.from_user.profile_image.url }}">
                {% endif %}
                <div class="relationship-info">
                    <span>{{relationship.from_user.username}}</span>
                    <span>{{relationship.created|date:"y.m.d"}}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

04.Web/web_project5/templates/users/following.html
{% extends 'base_profile.html' %}

{% block bottom_data %}

<div class="relationships">
    <h3>Following</h3>
    {% for relationship in relationships %}
        <div class="relationship">
            <a href="{% url 'users:profile' user_id=relationship.to_user.id %}">
                {% if relationship.to_user.profile_image %}
                    <img src="{{ relationship.to_user.profile_image.url }}">
                {% endif %}
                <div class="relationship-info">
                    <span>{{relationship.to_user.username}}</span>
                    <span>{{relationship.created|date:"y.m.d"}}</span>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock %}

04.Web/web_project5/templates/users/login.html
{% extends 'base.html' %}

{%block content%}
        <div id="login">
        <form method = "POST">
            <h1>Pystagram</h1>
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-login">로그인</button>
            <a href="{% url 'users:signup' %}">회원가입</a>
        </form>
        </div>
{% endblock %}

04.Web/web_project5/templates/users/profile.html
{%extends 'base_profile.html'%}

{%block bottom_data%}

<!--사용자가 작성한 Post 목록-->
<div class="post-grid-container">
    {% for post in user.post_set.all %}
        {% if post.postimage_set.first %}
            {% if post.postimage_set.first.photo%}
                <div class = "post-grid">
                    <a href="{%url 'posts:post_detail' post_id=post.id%}">
                        <img src="{{ post.postimage_set.first.photo.url }}" alt="">
                    </a>
                </div>
            {% endif %}
        {% endif %}
    {% endfor %}
</div>


{%endblock%}

04.Web/web_project5/templates/users/signup.html
{% extends 'base.html' %}

{%block content%}
    <body>
        <div id = "signup">
            <form method="POST" enctype="multipart/form-data">
                <h1>Pystagram</h1>
                {%csrf_token%}
                {{form.as_p}}
                <button type="submit" class="btn btn-signup">회원가입</button>
                <a href="{% url 'users:login' %}">로그인</a>
            </form>
            </div>
{% endblock %}